### PR TITLE
Add helper methods in PluginSettings

### PR DESCRIPTION
**Pull request by yadavcbala**
*Issue #, if available:*

*Description of changes:*
* Add helper method to PluginSettings for type specific attribute returns

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kowshikn** [comment]
Awesome, could you add Boolean alone for now?

**Review by chenqi0805 — COMMENTED** [review]
It will be great if we also have `getLongOrDefault`, which will facilitate bulk_size of ES sink.

**Review by chenqi0805 — APPROVED** [review]

**Comment by kowshikn** [comment]
@chenqi0805 Are we not doing MB for BulkSize? (Adding Long is fine, I didn't propose long because I couldn't see any use case where we will need Long)

**Review by kowshikn — APPROVED** [review]
:yay:

**Pull request merged**
